seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: outdir
      name: rut5-small
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        filename: checkpoint_{epoch:02d}-{val_loss:03.3f}
        save_last: true
        save_top_k: 1
        every_n_epochs: 1
        save_on_train_epoch_end: false
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        check_on_train_epoch_end: false
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 35
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
model:
  seed: 42
  model_name_or_path: cointegrated/rut5-small
  data_dir: 'data/processed'
  spec_tokens_dict:
    prefixes:
      knowledge_extraction: '|knowledge_extraction|:'
      knowledge_retrieval: '|knowledge_retrieval|:'
      knowledge_ground_generation: '|knowledge_ground_generation|:'
    separators:
      U: '[User]'
      S: '[Model]'
      gk: '[GK]'
  lr: 5.0e-05
  num_warmup_steps: 100

project_name: Persona Chat
experiment_name: rut5-small
clearml_tags: 
- rut5-small
log_to_clearml: false
clearml_api_host: http://nid-nlu-u20-clearml.ad.speechpro.com:8008
clearml_web_host: http://nid-nlu-u20-clearml.ad.speechpro.com:8080
clearml_files_host: http://nid-nlu-u20-clearml.ad.speechpro.com:8081
ckpt_path: null
